"use client";
import Link from "next/link";
import { useClock } from "@/hooks/use-clock";
import { useState } from "react";
import { ArrowUpRight, History as HistoryIcon } from "lucide-react";
import { useOwnerData } from "@/store/demo-store";
import { stationService } from "@/lib/services/stations";
import { dateTime } from "@/lib/services/booking-rules";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
export function History(){const now=useClock();const d=useOwnerData();const[query,setQuery]=useState("");const[status,setStatus]=useState("all");const[period,setPeriod]=useState("all");if(!d)return null;const sessions=d.sessions.filter(s=>(status==="all"||s.status===status)&&(period==="all"||now-new Date(s.createdAt).getTime()<=Number(period)*86400000)&&`${s.id} ${stationService.get(s.stationId)?.name} ${d.vehicles.find(v=>v.id===s.vehicleId)?.name}`.toLowerCase().includes(query.toLowerCase()));return <><div className="owner-heading"><div><h1>A record of better journeys.</h1><p>Look back at every session and every kilowatt-hour.</p></div></div><div className="panel"><div className="flex flex-wrap gap-3 mb-6"><Input className="flex-1 min-w-[180px]" aria-label="Search sessions" placeholder="Search station, vehicle, or session" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Session status" className="filter-control" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All sessions</option><option value="completed">Completed</option><option value="charging">Charging</option><option value="paused">Paused</option></select><select aria-label="History period" className="filter-control" value={period} onChange={e=>setPeriod(e.target.value)}><option value="all">All time</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option></select></div><div className="table-wrap"><Table><TableHeader><TableRow><TableHead>Station</TableHead><TableHead>Date</TableHead><TableHead>Energy</TableHead><TableHead>Duration</TableHead><TableHead>Solar mix</TableHead><TableHead>Status</TableHead><TableHead>Details</TableHead></TableRow></TableHeader><TableBody>{sessions.map(s=><TableRow key={s.id}><TableCell><strong className="text-xs font-medium">{stationService.get(s.stationId)?.name}</strong><span className="text-[10px] block muted mt-1">{s.id}</span></TableCell><TableCell className="text-[11px] muted">{dateTime(s.createdAt)}</TableCell><TableCell className="text-xs">{s.energy.toFixed(2)} kWh</TableCell><TableCell className="text-xs">{Math.floor(s.elapsed/60)} min</TableCell><TableCell className="text-xs text-green-800">{s.solar}%</TableCell><TableCell className="capitalize text-[11px]">{s.status}</TableCell><TableCell><Link href={`/charging/${s.id}`} aria-label={`View session ${s.id}`}><ArrowUpRight size={16}/></Link></TableCell></TableRow>)}</TableBody></Table></div>{!sessions.length&&<div className="empty-state"><HistoryIcon className="mx-auto muted"/><h3>No sessions in this view.</h3><p>Your charging history starts with your first session.</p><Link href="/bookings" className="action action-primary">View my bookings</Link></div>}<div className="flex justify-between border-t mt-6 pt-4 text-xs muted"><span>{sessions.length} sessions</span><span>{sessions.reduce((n,s)=>n+s.energy,0).toFixed(2)} kWh delivered</span></div></div></>;}
