"use client";
import { useState } from "react";
import { useCreditData } from "@/store/credit-store";
import { creditService } from "@/lib/credit/services";
import { credits } from "@/lib/credit/money";
import { isDemo } from "@/lib/config";
import { DataGrid, ConfirmAction } from "@/components/admin/shared";
import { Sheet, SheetContent, SheetTitle, SheetDescription } from "@/components/ui/sheet";
import { Input } from "@/components/ui/input";
import { ChargingReceipt, TopupReceipt } from "./receipt";
import { Heading, Source, timestamp } from "./ui";
export function AdminSessions() {
  const data = useCreditData(); const [selected,setSelected] = useState(""); const [status,setStatus] = useState("all"); const [reason,setReason]=useState(""); const session = data.sessions.find(s => s.id === selected);
  return <><Heading title="Energy, in real time." description="Charging state, station confirmation, credit costs and final stop reasons." /><DataGrid name="sessions" rows={data.sessions.filter(s => status === "all" || (status === "active" ? s.state !== "completed" : s.state === "completed"))} columns={[{label:"Session",value:s=>s.id},{label:"Owner",value:s=>data.users.find(u=>u.id===s.ownerId)?.name??s.ownerId},{label:"Bay",value:s=>s.bayId},{label:"State",value:s=>s.stopReason??s.state},{label:"Energy",value:s=>`${(s.energyMWh/1000000).toFixed(3)} kWh`},{label:"Cost",value:s=>credits(s.costMinor)}]} filters={<select className="credit-filter" aria-label="Session status" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All sessions</option><option value="active">Active</option><option value="completed">Completed</option></select>} onInspect={s=>{setSelected(s.id);setReason("");}} /><Sheet open={Boolean(session)} onOpenChange={v=>{if(!v){setSelected("");setReason("");}}}><SheetContent className="admin-detail-sheet"><SheetTitle>Session details</SheetTitle><SheetDescription>Station events and credit settlement are retained together.</SheetDescription>{session && <><ChargingReceipt sessionId={session.id} />{session.state!=="completed"&&<><label className="credit-form">Required safety reason<Input minLength={8} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Why this session must stop" /></label><ConfirmAction label="Stop session" title="Stop this session as Admin?" description="Send STOP and wait for acknowledgement, then post the final credit debit with this audit reason." disabled={reason.trim().length<8} action={()=>creditService.charging.stop(session.id,false,reason)}/></>}<div className="credit-timeline">{session.events.slice().reverse().map((e,i)=><p key={i}>{e.message.replaceAll("ESP32", "Station Controller")}<small>{timestamp(e.at)}</small></p>)}</div></>}</SheetContent></Sheet></>;
}
export function AdminPayments() {
  const data = useCreditData(); const [status,setStatus] = useState("all"); const [selected,setSelected] = useState(""); const payment=data.payments.find(p=>p.id===selected);
  return <><Heading title="Verified before credited." description="SSLCOMMERZ Sandbox transactions. Browser callbacks never act as proof of payment."/><DataGrid name="sandbox payments" rows={data.payments.filter(p=>status==="all"||p.status===status)} columns={[{label:"Reference",value:p=>p.id},{label:"Owner",value:p=>data.users.find(u=>u.id===p.userId)?.name??p.userId},{label:"Amount",value:p=>credits(p.amountMinor)},{label:"Status",value:p=>p.status},{label:"Source",value:()=>"SANDBOX"},{label:"Created",value:p=>timestamp(p.createdAt)}]} filters={<select className="credit-filter" aria-label="Payment status" value={status} onChange={e=>setStatus(e.target.value)}>{["all","pending","verified","failed","cancelled"].map(v=><option key={v}>{v}</option>)}</select>} onInspect={p=>setSelected(p.id)}/><Sheet open={Boolean(payment)} onOpenChange={v=>{if(!v)setSelected("");}}><SheetContent className="admin-detail-sheet"><SheetTitle>Sandbox payment</SheetTitle><SheetDescription>Only a verified transaction has a matching posted top-up ledger entry.</SheetDescription>{payment&&<><TopupReceipt paymentId={payment.id} /><p className="break-all no-print">{payment.id}</p><div className="data-row"><span>Amount</span><strong>{credits(payment.amountMinor)}</strong></div><div className="data-row"><span>Status</span><strong>{payment.status}</strong></div><div className="data-row"><span>Ledger credit</span><strong>{data.ledger.some(l=>l.reference===payment.id)?"Posted once":"Not credited"}</strong></div><p className="notice">{isDemo?"Local gateway simulation — not a real provider transaction.":"The backend validates provider status, currency and amount before posting credit."}</p></>}</SheetContent></Sheet></>;
}
export function AdminFaults() {
  const data = useCreditData(); const [filter,setFilter] = useState("all"); const [selected,setSelected]=useState(""); const [note,setNote]=useState(""); const fault=data.faults.find(f=>f.id===selected);
  return <><Heading title="Safe energy starts with attention." description="Triage faults, record inspection notes and follow the operational audit trail."/><DataGrid name="faults" rows={data.faults.filter(f=>filter==="all"||f.status===filter)} columns={[{label:"Fault",value:f=>f.message},{label:"Controller / bay",value:f=>`${f.deviceId} / ${f.bayId??"station"}`},{label:"Severity",value:f=>f.severity},{label:"Status",value:f=>f.status},{label:"Detected",value:f=>timestamp(f.at)}]} filters={<select className="credit-filter" aria-label="Fault status" value={filter} onChange={e=>setFilter(e.target.value)}>{["all","open","acknowledged","resolved"].map(s=><option key={s}>{s}</option>)}</select>} onInspect={f=>{setSelected(f.id);setNote(f.note);}}/><section className="credit-page-section"><h2 className="text-xl mb-5">Audit trail</h2><DataGrid name="audit trail" rows={data.audit} columns={[{label:"Action",value:a=>a.action},{label:"Actor",value:a=>a.actorId},{label:"Reference",value:a=>a.reference},{label:"Reason",value:a=>a.reason.replaceAll("ESP32", "Station Controller").replace(/relay/gi, "bay assignment")},{label:"Recorded",value:a=>timestamp(a.at)}]}/></section><Sheet open={Boolean(fault)} onOpenChange={v=>{if(!v)setSelected("");}}><SheetContent className="admin-detail-sheet"><SheetTitle>Inspect fault</SheetTitle><SheetDescription>A meaningful note is required to acknowledge or resolve.</SheetDescription>{fault&&<><h2>{fault.message}</h2><Source>{fault.severity}</Source><p className="text-xs muted">{timestamp(fault.at)} · {fault.deviceId}</p><label className="credit-form">Inspection / resolution note<Input value={note} onChange={e=>setNote(e.target.value)}/></label><ConfirmAction label="Acknowledge fault" title="Acknowledge this fault?" description="Acknowledgement records ownership; it does not clear the bay fault." disabled={fault.status!=="open"} action={()=>creditService.admin.fault(fault.id,"acknowledged",note)}/><ConfirmAction label="Resolve fault" title="Confirm inspection and resolution?" description="Resolved faults allow the bay to charge again, subject to all other safety checks." disabled={fault.status==="resolved"} action={()=>creditService.admin.fault(fault.id,"resolved",note)}/></>}</SheetContent></Sheet></>;
}
