"use client";
import { EnergyOverview, StationEnergyMonitor } from "@/components/energy/energy-monitor";
import { useState } from "react";
import Link from "next/link";
import dynamic from "next/dynamic";
import { Activity, Wallet, Radio, Zap, ArrowUpRight } from "lucide-react";
import { useCreditData } from "@/store/credit-store";
import { credits, decimal, parseCredits } from "@/lib/credit/money";
import { availableBays, walletView } from "@/lib/credit/selectors";
import { creditService } from "@/lib/credit/services";
import { isDemo } from "@/lib/config";
import { DataGrid, ConfirmAction, useUnsaved } from "@/components/admin/shared";
import { Input } from "@/components/ui/input";
import { Heading, Source } from "./ui";
const Chart = dynamic(() => import("@/components/owner/analytics-chart"), { ssr: false });

export function AdminOverview() {
  const data = useCreditData(); const active = data.sessions.filter(s => s.state !== "completed"); const online = data.devices.filter(d => d.online).length;
  const paid = data.payments.filter(p => p.status === "verified").reduce((sum,p) => sum+p.amountMinor,0);
  return <><Heading title="A clearer view of the network." description="Station health, prepaid energy and the people behind every charge." action={<Link className="action action-primary" href="/admin/devices">Open control room <ArrowUpRight size={16}/></Link>}/><div className="metric-grid">{[[Radio,`${online}/${data.devices.length}`,"Controllers online"],[Activity,String(active.length),"Active sessions"],[Wallet,credits(paid),"Verified sandbox top-ups"],[Zap,String(data.faults.filter(f=>f.status!=="resolved").length),"Faults needing attention"]].map(([Icon,value,label])=>{const Symbol=Icon as typeof Radio;return <div className="metric-card" key={String(label)}><Symbol size={19}/><strong className="!text-2xl">{String(value)}</strong><small>{String(label)}</small></div>;})}</div><EnergyOverview /><div className="credit-split"><section className="panel"><div className="panel-top"><h2 className="panel-title">Station Controllers & bays</h2><Source>{isDemo?"Digital Twin":"BACKEND"}</Source></div>{data.stations.map(s=><Link className="data-row" href={`/admin/stations/${s.id}`} key={s.id}><span><strong className="text-foreground">{s.name}</strong><small className="block mt-1">{s.deviceId} · {s.online?"Online":"Offline"}</small></span><span>{availableBays(data,s.id).length} / {data.bays.filter(b=>b.stationId===s.id).length} bays free <ArrowUpRight className="inline" size={14}/></span></Link>)}</section><section className="panel"><h2 className="panel-title">Operations shortcuts</h2>{[["/admin/users","Users & audited credit adjustments"],["/admin/wallet-transactions","Full wallet ledger"],["/admin/payments","SSLCOMMERZ Sandbox payments"],["/admin/faults","Faults & audit trail"],["/admin/settings","Tariffs & demo speed"]].map(([href,title])=><Link key={href} href={href} className="data-row"><span>{title}</span><ArrowUpRight size={16}/></Link>)}<p className="notice mt-5">Each station has one primary controller. Bay numbers are unique within that station. A command is not an acknowledgement.</p></section></div></>;
}

export function AdminAnalytics() {
  const data=useCreditData(); const [period,setPeriod]=useState("all"); const [energyStation,setEnergyStation]=useState("");
  const cutoff=period==="all"?0:Date.parse(data.lastTick)-Number(period)*86400000;
  const sessions=data.sessions.filter(s=>s.state==="completed"&&Date.parse(s.completedAt??s.updatedAt)>=cutoff);
  const spent=sessions.reduce((sum,s)=>sum+s.costMinor,0); const energy=sessions.reduce((sum,s)=>sum+s.energyMWh,0);
  const available=data.users.reduce((sum,u)=>sum+walletView(data,u.id).availableMinor,0);
  const rows=data.stations.map(s=>({id:s.id,name:s.name,energy:sessions.filter(c=>c.stationId===s.id).reduce((sum,c)=>sum+c.energyMWh,0),cost:sessions.filter(c=>c.stationId===s.id).reduce((sum,c)=>sum+c.costMinor,0),count:sessions.filter(c=>c.stationId===s.id).length}));
  return <><Heading title="Energy with a paper trail." description="Delivered energy and settled credit costs. Pending payments are excluded." action={<select className="credit-filter" aria-label="Analytics period" value={period} onChange={e=>setPeriod(e.target.value)}><option value="all">All time</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option></select>}/><div className="metric-grid">{[[`${(energy/1000000).toFixed(3)} kWh`,"Delivered energy"],[credits(spent),"Settled charging spend"],[String(sessions.length),"Completed sessions"],[credits(available),"Available wallet credit"]].map(([value,label])=><div className="metric-card" key={label}><small>{label}</small><strong className="!text-2xl">{value}</strong></div>)}</div><section className="panel mb-6"><div className="panel-top"><h2 className="panel-title">Delivered energy by station</h2><Source>{isDemo?"Digital Twin":"BACKEND"}</Source></div>{sessions.length?<Chart data={rows.map(r=>({label:r.name.replace("HelioBay ",""),value:r.energy/1000000}))}/>:<p className="notice">Complete a charging session to start building your network analytics.</p>}</section><section className="panel mb-6"><label className="credit-form">Station energy history<select aria-label="Analytics energy station" value={energyStation || data.stations[0]?.id || ""} onChange={e => setEnergyStation(e.target.value)}>{data.stations.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label></section><StationEnergyMonitor key={energyStation || data.stations[0]?.id} stationId={energyStation || data.stations[0]?.id || ""} /><DataGrid name="station analytics" rows={rows} columns={[{label:"Station",value:r=>r.name},{label:"Sessions",value:r=>r.count},{label:"Energy",value:r=>`${(r.energy/1000000).toFixed(3)} kWh`},{label:"Settled cost",value:r=>credits(r.cost)}]}/></>;
}

export function AdminSettings() {
  const data=useCreditData(); const [tariff,setTariff]=useState(decimal(data.policy.defaultTariffMinor)); const [maximum,setMaximum]=useState(decimal(data.policy.maxTopupMinor)); const [speed,setSpeed]=useState(data.policy.demoSpeed); const [timeout,setTimeoutValue]=useState(String(data.policy.communicationTimeoutMs/1000)); const [dirty,setDirty]=useState(false); useUnsaved(dirty);
  const save=async()=>{await creditService.admin.policy({...data.policy,defaultTariffMinor:parseCredits(tariff),maxTopupMinor:parseCredits(maximum),demoSpeed:speed,communicationTimeoutMs:Number(timeout)*1000});setDirty(false);};
  return <><Heading title="A considered set of controls." description="Configure credit policy, charging tariffs and communication safety. Every change is audited."/><div className="credit-split"><section className="panel credit-form"><h2 className="panel-title">Credit & tariff policy</h2><label>Default Credits per kWh<Input value={tariff} inputMode="decimal" onChange={e=>{setTariff(e.target.value);setDirty(true);}}/></label><label>Maximum top-up (Credits)<Input value={maximum} inputMode="decimal" onChange={e=>{setMaximum(e.target.value);setDirty(true);}}/></label><p className="text-xs muted">Minimum top-up is always 10.00 Credits. Policy changes apply to new sessions only; active session tariffs stay locked.</p><label>Communication timeout (seconds)<Input type="number" min="5" max="120" value={timeout} onChange={e=>{setTimeoutValue(e.target.value);setDirty(true);}}/></label>{isDemo&&<><Source>Digital Twin · simulation controls</Source><label>Simulation time speed<select aria-label="Simulation time speed" value={speed} onChange={e=>{setSpeed(Number(e.target.value) as 1|10|60);setDirty(true);}}><option value="1">1× — normal</option><option value="10">10× — accelerated</option><option value="60">60× — presentation</option></select></label><p className="text-xs muted">A station-level digital twin models EV demand and energy storage. Speed changes remain smooth and bounded; no physical controller is connected.</p></>}<ConfirmAction label="Save policy" title="Apply tariff and credit policy?" description="The default tariff updates all station tariffs for future sessions. Existing sessions keep their quoted rate." action={save}/><ConfirmAction label="Restore previous policy" title="Restore the preceding policy?" description="This is an audited rollback, not a ledger or balance reset." disabled={!data.previousPolicy} action={async()=>{await creditService.admin.policy(data.policy,true);const restored=data.previousPolicy!;setTariff(decimal(restored.defaultTariffMinor));setMaximum(decimal(restored.maxTopupMinor));setSpeed(restored.demoSpeed);setTimeoutValue(String(restored.communicationTimeoutMs/1000));setDirty(false);}}/></section><section className="panel self-start"><h2 className="panel-title">Connection & trust boundaries</h2>{[["Application mode",isDemo?"Digital Twin":"API"],["Authentication","Firebase ID token"],["Payment provider","SSLCOMMERZ Sandbox"],["Settlement","Verified by backend / IPN"],["Device transport","Backend → Station Controller"],["Controller model","One primary Station Controller per station"],["Wallet precision","Integer minor units · 2 decimals"]].map(([label,value])=><div className="data-row" key={label}><span>{label}</span><span>{value}</span></div>)}<p className="notice mt-5">Provider credentials, Firebase Admin credentials, controller credentials and safety must remain on the backend or device. The browser never acts as a payment or hardware authority.</p></section></div></>;
}
