"use client";
import { StationEnergyMonitor } from "@/components/energy/energy-monitor";
import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { Plus, Cpu } from "lucide-react";
import { useCreditData } from "@/store/credit-store";
import { creditService } from "@/lib/credit/services";
import { credits, decimal, parseCredits } from "@/lib/credit/money";
import { availableBays, bayState } from "@/lib/credit/selectors";
import type { Station, Bay } from "@/lib/credit/model";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { DataGrid, ConfirmAction, useUnsaved } from "@/components/admin/shared";
import { Heading, Source } from "./ui";
function Editor({ initial, close }: { initial: Station; close: () => void }) {
  const [draft, setDraft] = useState(initial); const [price, setPrice] = useState(decimal(initial.priceMinor)); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const canClose = useUnsaved(JSON.stringify(draft) !== JSON.stringify(initial) || price !== decimal(initial.priceMinor));
  return <Dialog open onOpenChange={v => { if (!v && !busy && canClose()) close(); }}><DialogContent className="max-h-[90dvh] overflow-auto"><DialogTitle>Station configuration</DialogTitle><DialogDescription>One Station Controller coordinates the station’s charging bays.</DialogDescription><form className="credit-form" onSubmit={async e => { e.preventDefault(); setBusy(true); try { await creditService.stations.save({ ...draft, priceMinor: parseCredits(price) }); close(); toast.success("Station saved."); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}>
    {([ ["name","Station name"], ["address","Address"], ["landmark","Landmark"], ["deviceId","Controller ID"], ["openingHours","Opening hours"] ] as const).map(([key,label]) => <label key={key}>{label}<Input required value={draft[key]} onChange={e => setDraft({ ...draft, [key]: e.target.value })} /></label>)}<div className="grid grid-cols-2 gap-3">{([ ["lat","Latitude"], ["lng","Longitude"], ["powerKw","Maximum power (kW)"], ["solarPercent","Solar availability (%)"] ] as const).map(([key,label]) => <label key={key}>{label}<Input type="number" step="any" required value={draft[key]} onChange={e => setDraft({ ...draft, [key]: Number(e.target.value) })} /></label>)}</div><label>Tariff (Credits / kWh)<Input inputMode="decimal" value={price} onChange={e => setPrice(e.target.value)} /></label>{error && <p role="alert" className="error-text">{error}</p>}<Button type="submit" disabled={busy}>{busy ? "Saving…" : "Save station"}</Button></form></DialogContent></Dialog>;
}
export function AdminStations({ id }: { id?: string }) {
  const data = useCreditData(); const router = useRouter(); const [edit, setEdit] = useState<Station | null>(null); const [filter, setFilter] = useState("all"); const station = data.stations.find(s => s.id === id);
  return <><Heading title={id ? station?.name ?? "Station not found" : "Places that power possibility."} description="One Station Controller coordinates solar, storage, grid exchange and charging bays." action={<Button onClick={() => setEdit({ id: `station-${crypto.randomUUID().slice(0,8)}`, name: "HelioBay ", address: "", landmark: "", lat: 23.7937, lng: 90.4066, deviceId: `ST-${crypto.randomUUID().slice(0,6)}`, online: true, priceMinor: data.policy.defaultTariffMinor, powerKw: 60, solarPercent: 90, image: "/images/station.webp", amenities: ["Wi-Fi"], openingHours: "07:00–22:00" })}><Plus size={15} />Add station</Button>} />{!id ? <DataGrid name="stations" rows={data.stations.filter(s => filter === "all" || (filter === "online" ? s.online : !s.online))} columns={[{ label: "Station", value: s => s.name }, { label: "Station Controller", value: s => s.deviceId }, { label: "Available bays", value: s => availableBays(data,s.id).length }, { label: "Tariff", value: s => credits(s.priceMinor) }, { label: "Status", value: s => s.online ? "Online" : "Offline" }]} onInspect={s => router.push(`/admin/stations/${s.id}`)} filters={<select className="credit-filter" aria-label="Station status" value={filter} onChange={e => setFilter(e.target.value)}><option value="all">All stations</option><option value="online">Online</option><option value="offline">Offline</option></select>} /> : station && <><section className="panel mb-6"><Cpu size={25} className="text-green-700" /><div className="data-row"><span>Address</span><strong>{station.address}</strong></div><div className="data-row"><span>Controller ID</span><strong>{station.deviceId}</strong></div><div className="data-row"><span>Tariff</span><strong>{credits(station.priceMinor)}/kWh</strong></div><div className="credit-actions mt-5"><Button onClick={() => setEdit(station)}>Edit station</Button><ConfirmAction label={station.online ? "Take station offline" : "Bring station online"} title="Change station availability?" description="Taking this station offline ends active demo charging sessions and settles their credit costs." danger={station.online} action={() => creditService.stations.save({ ...station, online: !station.online })} /><Link className="action action-outline" href={`/stations/${station.id}`}>Owner view</Link></div></section><StationEnergyMonitor stationId={id} /><AdminBays stationId={id} /></>}{edit && <Editor initial={edit} close={() => setEdit(null)} />}</>;
}
export function AdminBays({ stationId }: { stationId?: string }) {
  const data = useCreditData(); const [edit, setEdit] = useState<Bay | null>(null); const [error,setError] = useState(""); const [busy,setBusy] = useState(false); const [filter,setFilter] = useState(stationId ?? "all");
  const rows = data.bays.filter(b => filter === "all" || b.stationId === filter);
  return <><Heading level={stationId ? 2 : 1} title="Every bay, connected." description="Bay numbers are unique within each station." action={<Button onClick={() => { const station = data.stations.find(s => s.id === filter) ?? data.stations[0]; if (!station) return; const number = Math.max(0,...data.bays.filter(b => b.stationId === station.id).map(b => b.number)) + 1; setEdit({ id: `${station.id}-BAY${number}`, stationId: station.id, deviceId: station.deviceId, number, relayChannel: number, connector: "CCS2", enabled: true, plugged: false, fault: false }); setError(""); }}>Add bay</Button>} /><DataGrid name="bays" rows={rows} columns={[{ label: "Bay", value: b => `Bay ${b.number}` }, { label: "Station", value: b => data.stations.find(s => s.id === b.stationId)?.name ?? b.stationId }, { label: "Controller ID", value: b => b.deviceId }, { label: "Connector", value: b => b.connector }, { label: "State", value: b => bayState(data,b) }]} filters={!stationId && <select className="credit-filter" aria-label="Bay station filter" value={filter} onChange={e => setFilter(e.target.value)}><option value="all">All stations</option>{data.stations.map(s => <option value={s.id} key={s.id}>{s.name}</option>)}</select>} onInspect={b => { setEdit(b); setError(""); }} /><Dialog open={Boolean(edit)} onOpenChange={v => { if (!v && !busy) setEdit(null); }}><DialogContent><DialogTitle>Bay configuration</DialogTitle><DialogDescription>The Station Controller is inherited from the station. No extra Station Controller is assigned to a bay.</DialogDescription>{edit && <><Source>{edit.deviceId}</Source><form className="credit-form" onSubmit={async e => { e.preventDefault(); setBusy(true); try { await creditService.bays.save(edit); setEdit(null); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}><label>Bay number<Input type="number" min="1" value={edit.number} onChange={e => setEdit({ ...edit, number: Number(e.target.value) })} /></label><label>Bay connector<select value={edit.connector} onChange={e => setEdit({ ...edit, connector: e.target.value as Bay["connector"] })}><option>CCS2</option><option>Type 2</option></select></label>{error && <p className="error-text" role="alert">{error}</p>}<Button type="submit" disabled={busy}>Save bay configuration</Button></form><ConfirmAction label={edit.enabled ? "Disable bay" : "Enable bay"} title="Change bay availability?" description="Disabling a bay safely ends its active demo session and releases remaining held credits." danger={edit.enabled} action={async () => { await creditService.bays.save({ ...edit, enabled: !edit.enabled }); setEdit(null); }} /></>}</DialogContent></Dialog></>;
}
