"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { z } from "zod";
import { toast } from "sonner";
import { backend } from "@/lib/api/backend";
import { creditService } from "@/lib/credit/services";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog,DialogContent,DialogTitle,DialogDescription } from "@/components/ui/dialog";
import { DataGrid,ConfirmAction } from "@/components/admin/shared";
import { Heading,Action } from "./ui";
import { StationEnergyMonitor } from "@/components/energy/energy-monitor";

type Resource="stations"|"bays"|"devices"|"tariffs";
type Row={id:string}&Record<string,unknown>;
type Field={key:string;label:string;type?:"number"|"boolean";choices?:string[];relation?:Resource;optional?:boolean};
const rowSchema=z.object({id:z.string()}).passthrough();
const fields:Record<Resource,Field[]>={
  stations:[{key:"code",label:"Station code"},{key:"name",label:"Station name"},{key:"address",label:"Address"},{key:"latitude",label:"Latitude",type:"number"},{key:"longitude",label:"Longitude",type:"number"},{key:"tariffId",label:"Charging tariff",relation:"tariffs"},{key:"primaryDeviceId",label:"Primary Station Controller",relation:"devices",optional:true},{key:"status",label:"Operating status",choices:["OFFLINE","ONLINE","MAINTENANCE"]},{key:"isOpen",label:"Open for charging",type:"boolean"},{key:"openingHours",label:"Opening hours",optional:true},{key:"solarCapable",label:"Solar capable",type:"boolean"},{key:"batteryCapable",label:"Battery storage",type:"boolean"}],
  bays:[{key:"code",label:"Bay code"},{key:"stationId",label:"Station",relation:"stations"},{key:"deviceId",label:"Station Controller",relation:"devices"},{key:"number",label:"Bay number",type:"number"},{key:"relayChannel",label:"Controller output assignment",type:"number"},{key:"connectorType",label:"Connector",choices:["CCS2","TYPE_2","CHADEMO","AC_SOCKET"]},{key:"maxPowerW",label:"Maximum power (W)",type:"number"},{key:"enabled",label:"Enabled for charging",type:"boolean"}],
  devices:[{key:"publicId",label:"Controller ID"},{key:"stationId",label:"Assigned station",relation:"stations"},{key:"mqttClientId",label:"Controller connection identity"},{key:"firmwareVersion",label:"Controller firmware",optional:true},{key:"credentialRef",label:"Protected credential reference (secret://…)",optional:true}],
  tariffs:[{key:"name",label:"Tariff name"},{key:"priceMinorPerKwh",label:"Price (poisha / kWh; 100 poisha = 1 Credit)",type:"number"},{key:"active",label:"Available for new charging",type:"boolean"}],
};
const names={stations:"Stations",bays:"Charging bays",devices:"Station Controllers",tariffs:"Charging tariffs"};
const display=(value:unknown)=>value==null?"Not assigned":typeof value==="boolean"?value?"Yes":"No":String(value);
export function ApiAdminResources({resource,stationId}:{resource:Resource;stationId?:string}){
  const [rows,setRows]=useState<Row[]>([]),[relations,setRelations]=useState<Partial<Record<Resource,Row[]>>>({}),[draft,setDraft]=useState<Row|null>(null),[reason,setReason]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[version,setVersion]=useState(0);
  useEffect(()=>{const controller=new AbortController();void Promise.all([backend.all(`/admin/${resource}`,rowSchema,controller.signal),Promise.all([...new Set(fields[resource].flatMap(f=>f.relation?[f.relation]:[]))].map(async r=>[r,await backend.all(`/admin/${r}`,rowSchema,controller.signal)] as const))]).then(([items,lookups])=>{setRows(items);setRelations(Object.fromEntries(lookups));setError("");}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[resource,version]);
  const refresh=async()=>{await creditService.refresh();setVersion(v=>v+1);};
  const edit=(row:Row)=>{setDraft({...row});setReason("");setError("");};
  const create=()=>edit({id:"",stationId:stationId??"",status:"OFFLINE",isOpen:false,enabled:true,active:true,latitude:23.7806,longitude:90.4193,number:1,relayChannel:1,maxPowerW:7000,connectorType:"TYPE_2",priceMinorPerKwh:1800});
  async function save(){if(!draft)return;setBusy(true);setError("");try{
    if(reason.trim().length<8)throw new Error("Enter a meaningful reason of at least 8 characters.");
    const data:Record<string,unknown>={};
    for(const f of fields[resource]){if(f.key==="primaryDeviceId"&&!draft.id)continue;const value=draft[f.key];if(f.optional&&(value==null||value==="")){if(f.key==="primaryDeviceId"&&draft.id)data[f.key]=null;continue;}data[f.key]=f.type==="number"?Number(value):f.type==="boolean"?Boolean(value):value;}
    await backend.request(`/admin/${resource}${draft.id?`/${encodeURIComponent(draft.id)}`:""}`,z.unknown(),{method:draft.id?"PATCH":"POST",body:{data,reason}});
    setDraft(null);toast.success("Configuration saved and audited.");await refresh();
  }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <><Heading level={stationId?2:1} title={names[resource]} description="Backend configuration with validation, safe relationship checks and an immutable audit trail." action={<Button onClick={create}>Add {resource==="devices"?"Station Controller":resource.slice(0,-1)}</Button>}/>{loading?<p role="status" className="panel">Loading configuration…</p>:<DataGrid name={names[resource]} rows={rows.filter(r=>!stationId||r.stationId===stationId)} columns={fields[resource].filter(f=>!f.optional&&f.key!=="mqttClientId").slice(0,5).map(f=>({label:f.label,value:(r:Row)=>f.relation?display(relations[f.relation]?.find(p=>p.id===r[f.key])?.name??relations[f.relation]?.find(p=>p.id===r[f.key])?.publicId??r[f.key]):display(r[f.key])}))} onInspect={edit}/>} {!draft&&error&&<p role="alert" className="notice">{error} <Button variant="outline" onClick={()=>setVersion(v=>v+1)}>Retry</Button></p>}
    <Dialog open={Boolean(draft)} onOpenChange={open=>{if(!open&&!busy)setDraft(null);}}><DialogContent className="max-h-[90dvh] overflow-y-auto"><DialogTitle>{draft?.id?"Edit":"Create"} {resource==="devices"?"Station Controller":resource.slice(0,-1)}</DialogTitle><DialogDescription>Stop active charging before changing hardware assignments. Deletion is refused when historical records refer to this resource.</DialogDescription>{draft&&<form className="credit-form" onSubmit={e=>{e.preventDefault();void save();}}>{fields[resource].filter(f=>f.key!=="primaryDeviceId"||draft.id).map(f=><label key={f.key}>{f.label}{f.type==="boolean"?<input type="checkbox" checked={Boolean(draft[f.key])} onChange={e=>setDraft({...draft,[f.key]:e.target.checked})}/>:f.choices||f.relation?<select required={!f.optional} value={String(draft[f.key]??"")} onChange={e=>setDraft({...draft,[f.key]:e.target.value})}><option value="">{f.optional?"Not assigned":"Select…"}</option>{(f.choices??relations[f.relation!]?.filter(r=>f.relation!=="devices"||!draft.stationId&&resource!=="stations"||r.stationId===(resource==="stations"?draft.id:draft.stationId)).map(r=>r.id)??[]).map(v=><option key={v} value={v}>{f.relation?display(relations[f.relation]?.find(r=>r.id===v)?.name??relations[f.relation]?.find(r=>r.id===v)?.publicId??v):v}</option>)}</select>:<Input required={!f.optional} type={f.type==="number"?"number":"text"} step={f.key==="latitude"||f.key==="longitude"?"any":"1"} value={String(draft[f.key]??"")} onChange={e=>setDraft({...draft,[f.key]:e.target.value})}/>}</label>)}<label>Mandatory change reason<Input required minLength={8} value={reason} onChange={e=>setReason(e.target.value)}/></label>{error&&<p role="alert" className="error-text">{error}</p>}<Button type="submit" disabled={busy}>{busy?"Saving…":"Save configuration"}</Button>{draft.id&&<><ConfirmAction label="Delete resource" title="Delete this unused resource?" description="Records referenced by charging history cannot be deleted. The change and reason are audited." danger disabled={busy||reason.trim().length<8} action={async()=>{await backend.request(`/admin/${resource}/${encodeURIComponent(draft.id)}`,z.unknown(),{method:"DELETE",body:{reason}});setDraft(null);await refresh();}}/>{resource==="stations"&&<Link className="action action-outline" href={`/admin/stations/${draft.id}`}>Open station energy and bays</Link>}</>}</form>}</DialogContent></Dialog></>;
}
export function ApiStationDetail({id}:{id:string}){return <><Link href="/admin/stations" className="action action-outline mb-6">Station configuration</Link><StationEnergyMonitor stationId={id}/><ApiAdminResources resource="bays" stationId={id}/></>;}
export function ReconcileSession({id}:{id:string}){const [reason,setReason]=useState("");return <div className="credit-form"><label>Reconciliation reason<Input minLength={8} value={reason} onChange={e=>setReason(e.target.value)}/></label><Action disabled={reason.trim().length<8} run={async()=>{await backend.request(`/admin/charging-sessions/${encodeURIComponent(id)}/reconcile`,z.unknown(),{method:"POST",body:{reason,confirmed:true},idempotencyKey:crypto.randomUUID()});await creditService.refresh();}}>Request safe stop reconciliation</Action></div>;}
