"use client";
import { useEffect, useState, type ReactNode } from "react";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { LayoutDashboard, MapPin, Zap, Wallet, History, CarFront, UserRound, Users, Cpu, Grid2X2, Activity, Settings, Menu, Bell, Search, PanelLeftClose, LogOut } from "lucide-react";
import { useAuth } from "@/components/shared/providers";
import { Brand } from "@/components/shared/brand";
import { authService } from "@/lib/services/auth";
import { useCreditStore } from "@/store/credit-store";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Sheet, SheetContent, SheetTitle, SheetDescription } from "@/components/ui/sheet";
import { Skeleton } from "@/components/ui/skeleton";
import { Action, ConnectionError } from "./ui";
const ownerLinks = [ { href: "/dashboard", label: "Overview", icon: LayoutDashboard }, { href: "/stations", label: "Stations", icon: MapPin }, { href: "/charge", label: "Connect & start", icon: Zap }, { href: "/wallet", label: "Wallet", icon: Wallet }, { href: "/history", label: "Charging history", icon: History }, { href: "/vehicles", label: "Vehicles", icon: CarFront }, { href: "/profile", label: "Profile", icon: UserRound } ];
export const adminLinks = [ { href: "/admin", label: "Overview", icon: LayoutDashboard }, { href: "/admin/users", label: "Users", icon: Users }, { href: "/admin/stations", label: "Stations", icon: MapPin }, { href: "/admin/bays", label: "Bays", icon: Grid2X2 }, { href: "/admin/devices", label: "Controllers", icon: Cpu }, { href: "/admin/sessions", label: "Charging sessions", icon: Zap }, { href: "/admin/wallet-transactions", label: "Wallet ledger", icon: Wallet }, { href: "/admin/payments", label: "Sandbox payments", icon: Wallet }, { href: "/admin/analytics", label: "Analytics", icon: Activity }, { href: "/admin/faults", label: "Faults & audit", icon: Activity }, { href: "/admin/settings", label: "Settings", icon: Settings } ];
export function CreditShell({ children, admin = false }: { children: ReactNode; admin?: boolean }) {
  const { user, loading } = useAuth(); const path = usePathname(); const router = useRouter(); const state = useCreditStore();
  const [drawer, setDrawer] = useState(false); const [dialog, setDialog] = useState<"search" | "notifications" | "profile" | null>(null); const [query, setQuery] = useState(""); const [collapsed, setCollapsed] = useState(false);
  const links = admin ? adminLinks : ownerLinks;
  useEffect(() => { if (!loading && !user) router.replace(`/auth/sign-in?${admin ? "role=admin&" : ""}next=${encodeURIComponent(path)}`); if (!loading && !admin && user?.role === "admin") router.replace("/admin"); }, [user, loading, admin, path, router]);
  useEffect(() => { const key = (e: KeyboardEvent) => { if ((e.ctrlKey || e.metaKey) && e.key === "k") { e.preventDefault(); setDialog("search"); } }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, []);
  if (loading || !user) return <main className="container-wide py-16"><Skeleton className="h-12 w-64 mb-8" /><Skeleton className="h-80" /><p role="status">Loading your account…</p></main>;
  if (admin && user.role !== "admin") return <main className="empty-state" id="main-content"><h1>Administrator access required.</h1><p>Your owner account cannot access network controls.</p><Link className="action action-primary" href="/dashboard">Return to dashboard</Link></main>;
  const account = state.data.users.find(u => u.id === user.id);
  const nav = (mobile: boolean) => <nav aria-label={mobile ? `Mobile ${admin ? "admin" : "owner"} navigation` : `${admin ? "Admin" : "Owner"} navigation`}>{links.map(item => <Link key={item.href} title={item.label} href={item.href} className={`owner-nav-link ${path === item.href || item.href !== "/admin" && path.startsWith(`${item.href}/`) ? "active" : ""}`} onClick={() => setDrawer(false)}><item.icon size={18} /><span>{item.label}</span></Link>)}</nav>;
  return <div className={`owner-shell ${collapsed ? "credit-collapsed" : ""}`}>
    <aside className="owner-sidebar"><Brand /><div className="sidebar-label">{admin ? "STATION OPERATIONS" : "YOUR CHARGING COMPANION"}</div>{nav(false)}<div className="mt-auto pt-6"><Link className="owner-nav-link" href="/">Public website ↗</Link>{admin && <Button variant="ghost" onClick={() => setCollapsed(!collapsed)} aria-label="Collapse sidebar"><PanelLeftClose size={18} /><span>Collapse sidebar</span></Button>}<Action variant="ghost" run={() => authService.logout()}><LogOut size={16} /><span>Sign out</span></Action></div></aside>
    <div className="owner-body"><header className="owner-topbar"><div className="flex gap-2 items-center"><Button className="credit-mobile-menu" variant="ghost" size="icon" onClick={() => setDrawer(true)} aria-label={`Open ${admin ? "admin" : "owner"} navigation`}><Menu size={18} /></Button><span className="text-xs">{[...links].reverse().find(l => path.startsWith(l.href))?.label ?? "Your energy"}</span></div><div className="flex gap-2 items-center"><Button variant="ghost" size="icon" aria-label="Search navigation" onClick={() => setDialog("search")}><Search size={17} /></Button><Button variant="ghost" size="icon" aria-label="Notifications" onClick={() => setDialog("notifications")}><Bell size={17} /></Button><Button variant="ghost" aria-label="Profile menu" onClick={() => setDialog("profile")}><UserRound size={17} /><span className="hidden sm:inline text-xs">{account?.name.split(" ")[0] ?? user.name}</span></Button></div></header>
      <main className="owner-content" id="main-content">{state.loading ? <div className="panel"><Skeleton className="h-72" /><p role="status">Loading verified account data…</p></div> : state.error ? <div className="panel empty-state"><h1>Account data unavailable.</h1><p>{state.error}</p><ConnectionError /></div> : account?.status === "blocked" ? <div className="panel empty-state"><h1>Your account is blocked.</h1><p>Charging and wallet changes are paused. Contact the station operator to review your account.</p><Action run={() => authService.logout()}>Sign out</Action></div> : children}</main>
    </div>
    {!admin && <nav className="owner-bottom-nav" aria-label="Mobile quick navigation">{[ownerLinks[0], ownerLinks[1], ownerLinks[2], ownerLinks[3], ownerLinks[6]].map(l => <Link className={path.startsWith(l.href) ? "active" : ""} href={l.href} key={l.href}><l.icon size={20} />{l.href === "/charge" ? "Charge" : l.label}</Link>)}</nav>}
    <Sheet open={drawer} onOpenChange={setDrawer}><SheetContent className="p-6 overflow-y-auto"><SheetTitle>HelioBay navigation</SheetTitle><SheetDescription>Your energy, within reach.</SheetDescription>{nav(true)}</SheetContent></Sheet>
    <Dialog open={Boolean(dialog)} onOpenChange={v => { if (!v) setDialog(null); }}><DialogContent><DialogTitle>{dialog === "search" ? "Go somewhere brighter." : dialog === "notifications" ? "Your energy updates." : account?.name ?? user.name}</DialogTitle><DialogDescription>{dialog === "notifications" ? "Session, device and wallet activity." : "Manage your HelioBay account and navigation."}</DialogDescription>
      {dialog === "search" ? <><Input aria-label="Search navigation destinations" placeholder="Search pages…" value={query} onChange={e => setQuery(e.target.value)} />{links.filter(l => l.label.toLowerCase().includes(query.toLowerCase())).map(l => <Link key={l.href} href={l.href} className="owner-nav-link" onClick={() => setDialog(null)}><l.icon size={15} />{l.label}</Link>)}</> : dialog === "notifications" ? <><p className="notice">{state.data.sessions.filter(s => s.state !== "completed" && (admin || s.ownerId === user.id)).length} active sessions. {state.data.faults.filter(f => f.status !== "resolved").length} network alerts.</p><Link className="action action-outline" onClick={() => setDialog(null)} href={admin ? "/admin/faults" : "/history"}>View session updates</Link><Link className="action action-outline" onClick={() => setDialog(null)} href={admin ? "/admin/wallet-transactions" : "/wallet/transactions"}>View wallet activity</Link></> : <><p>{user.email}</p><Link href={admin ? "/admin/settings" : "/profile"} className="action action-outline" onClick={() => setDialog(null)}>Account settings</Link><Action variant="destructive" run={() => authService.logout()}>Sign out</Action></>}
    </DialogContent></Dialog>
  </div>;
}
