"use client";
import { useState } from "react";
import dynamic from "next/dynamic";
import Link from "next/link";
import { Heart, ArrowUpRight, Sun, MapPin, Zap } from "lucide-react";
import { useCreditData, useCreditStore } from "@/store/credit-store";
import { availableBays, bayState, distance, deviceFresh } from "@/lib/credit/selectors";
import { credits } from "@/lib/credit/money";
import { creditService } from "@/lib/credit/services";
import { isDemo } from "@/lib/config";
import { useClock } from "@/hooks/use-clock";
import type { Station } from "@/lib/credit/model";
import { PublicShell } from "@/components/shared/public-shell";
import { AssetImage } from "@/components/shared/asset-image";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { Sheet, SheetContent, SheetTitle, SheetDescription } from "@/components/ui/sheet";
import { Action, ConnectionError, Source, timestamp } from "./ui";
import { LocationPanel, useLocation } from "./location";
const Map = dynamic(() => import("./map"), { ssr: false, loading: () => <Skeleton className="h-full w-full" /> });
export function useNearest() { const data = useCreditData(); const location = useLocation(s => s.coordinates); return data.stations.map(s => ({ ...s, distanceKm: isDemo && location ? distance(location, s) : s.distanceKm })).sort((a, b) => (a.distanceKm ?? Infinity) - (b.distanceKm ?? Infinity)); }
export function StationCard({ station, selected = false, onSelect }: { station: Station; selected?: boolean; onSelect?: () => void }) {
  const data = useCreditData(); const clock = useClock(); const now = clock || Date.parse(data.lastTick); const account = useCreditStore(s => s.account); const user = data.users.find(u => u.id === account?.id); const fresh = deviceFresh(data,station.deviceId,now); const bays = data.bays.filter(b => b.stationId === station.id); const count = availableBays(data, station.id, now).length; const saved = user?.savedStations.includes(station.id);
  return <article className={`station-card credit-station-card ${selected ? "selected" : ""}`}><div className="station-card-photo"><AssetImage src={station.image} alt={`${station.name} solar canopy concept`} fill sizes="(max-width:600px)100vw,33vw" /><span className="absolute bottom-3 left-3"><Source>{isDemo ? "DEMO MODE" : "BACKEND DATA"}</Source></span></div><div className="station-card-body"><div className="flex justify-between gap-3"><h3>{station.name}</h3>{user && <Action run={() => creditService.users.update({ savedStations: saved ? user.savedStations.filter(id => id !== station.id) : [...user.savedStations, station.id] })}><Heart size={15} fill={saved ? "currentColor" : "none"} /><span className="sr-only">{saved ? "Unsave" : "Save"} {station.name}</span></Action>}</div><p className="text-xs muted mt-2">{station.address}</p><div className="credit-station-metrics"><span><MapPin size={12} className="inline mr-1" />{station.distanceKm == null ? "Share location for distance" : `${station.distanceKm.toFixed(1)} km · ~${Math.max(2, Math.ceil(station.distanceKm * 3))} min estimated`}</span></div><div className="data-row"><span>{station.online ? "Station online" : "Station offline"}</span><span>{fresh ? "Device online" : "Device offline / stale"}</span></div><div className="data-row"><span>{count}/{bays.length} bays available</span><strong>{credits(station.priceMinor)}/kWh</strong></div><p className="text-xs muted my-4"><Sun size={13} className="inline mr-1" />{station.solarPercent}% solar availability</p>{onSelect && <Button className="w-full mb-2" variant="outline" onClick={onSelect}>Show on map</Button>}<Link className="action action-dark" href={`/stations/${station.id}`}>View Station <ArrowUpRight size={14} /></Link></div></article>;
}
export function StationDiscovery() {
  const data = useCreditData(); const clock = useClock(); const now = clock || Date.parse(data.lastTick); const ready = useCreditStore(s => s.ready); const error = useCreditStore(s => s.error); const stations = useNearest(); const account = useCreditStore(s => s.account); const user = data.users.find(u => u.id === account?.id);
  const [query, setQuery] = useState(""); const [sort, setSort] = useState("nearest"); const [filter, setFilter] = useState("all"); const [map, setMap] = useState(false); const [selected, setSelected] = useState("green-point"); const [sheet, setSheet] = useState(false); const [connector, setConnector] = useState("all");
  const rows = stations.filter(s => `${s.name} ${s.address} ${s.landmark}`.toLowerCase().includes(query.toLowerCase()) && (filter !== "available" || availableBays(data, s.id, now).length > 0) && (filter !== "saved" || user?.savedStations.includes(s.id)) && (connector === "all" || data.bays.some(b => b.stationId === s.id && b.connector === connector))).sort((a, b) => sort === "cheapest" ? a.priceMinor - b.priceMinor : sort === "bays" ? availableBays(data, b.id, now).length - availableBays(data, a.id, now).length : sort === "renewable" ? b.solarPercent - a.solarPercent : (a.distanceKm ?? Infinity) - (b.distanceKm ?? Infinity));
  return <PublicShell><div className="container-wide credit-discovery"><div className="page-intro"><p className="eyebrow">A CLEANER STOP, NEAR YOU</p><h1>Find your next charge.</h1><p>Discover an available bay. Arrive, connect your plug and start with Credits.</p></div><ConnectionError /><LocationPanel /><div className="filter-bar"><Input aria-label="Search stations" placeholder="Station, address or landmark" className="max-w-sm" value={query} onChange={e => setQuery(e.target.value)} /><select className="credit-filter" aria-label="Station filter" value={filter} onChange={e => setFilter(e.target.value)}><option value="all">All stations</option><option value="available">Available now</option><option value="saved">Saved stations</option></select><select className="credit-filter" aria-label="Sort stations" value={sort} onChange={e => setSort(e.target.value)}><option value="nearest">Nearest</option><option value="cheapest">Cheapest</option><option value="bays">Available bays</option><option value="renewable">Renewable percentage</option></select><select className="credit-filter" aria-label="Connector filter" value={connector} onChange={e => setConnector(e.target.value)}><option value="all">All connectors</option><option>CCS2</option><option>Type 2</option></select><Button variant="outline" onClick={() => setMap(!map)}>{map ? "List view" : "Map view"}</Button></div>{!ready ? <Skeleton className="h-96" /> : error ? <div className="empty-state"><h2>Station data unavailable.</h2><p role="alert">{error}</p></div> : !rows.length ? <div className="empty-state"><h2>No stations match your search.</h2><Button variant="outline" onClick={() => { setQuery(""); setFilter("all"); setConnector("all"); }}>Clear filters</Button></div> : <div className={map ? "map-layout" : "credit-station-list"}><div className={map ? "map-results" : "contents"}>{rows.map(s => <StationCard key={s.id} station={s} selected={map && s.id === selected} onSelect={map ? () => setSelected(s.id) : undefined} />)}</div>{map && <div className="map-panel"><Map stations={rows} selected={selected} onSelect={id => { setSelected(id); if (window.innerWidth < 850) setSheet(true); }} /></div>}</div>}<Sheet open={sheet} onOpenChange={setSheet}><SheetContent side="bottom" className="max-h-[80dvh] overflow-auto p-5"><SheetTitle>Selected station</SheetTitle><SheetDescription>View availability and directions.</SheetDescription>{rows.find(s => s.id === selected) && <StationCard station={rows.find(s => s.id === selected)!} />}</SheetContent></Sheet></div></PublicShell>;
}
export function StationDetails({ id }: { id: string }) {
  const data = useCreditData(); const clock = useClock(); const now = clock || Date.parse(data.lastTick); const ready = useCreditStore(s => s.ready); const s = useNearest().find(s => s.id === id); const device = data.devices.find(d => d.id === s?.deviceId);
  if (!ready) return <PublicShell><div className="container-wide py-16"><Skeleton className="h-96" /></div></PublicShell>;
  if (!s) return <PublicShell><div className="empty-state"><h1>Station unavailable.</h1><ConnectionError /><Link className="action action-outline" href="/stations">Back to stations</Link></div></PublicShell>;
  return <PublicShell><div className="container-wide"><ConnectionError /><div className="page-intro"><Link className="text-xs muted" href="/stations">← All stations</Link><h1>{s.name}</h1><p>{s.address}</p></div><div className="detail-layout"><div><div className="detail-photo"><AssetImage src={s.image} alt={`${s.name} concept solar charging canopy`} fill priority sizes="(max-width:850px)100vw,60vw" /></div><p className="text-[10px] muted mt-2">Original concept imagery · {isDemo ? "Demo station" : "Architectural illustration"}</p><div className="metric-grid">{[["Solar availability", `${s.solarPercent}%`], ["Station battery", device ? `${device.stationBattery.toFixed(0)}%` : "Unavailable"], ["Charge rate", `${s.powerKw} kW`], ["Available bays", `${availableBays(data, id, now).length}`]].map(([l,v]) => <div key={l}><small className="muted">{l}</small><strong className="text-2xl block mt-2">{v}</strong></div>)}</div><h2 className="text-xl mb-5">Know your bay before you plug in.</h2><div className="credit-grid">{data.bays.filter(b => b.stationId === id).map(b => <Link className="credit-bay" href={`/charge?station=${id}&bay=${b.id}`} key={b.id}><Zap size={20} /><strong>Bay {String(b.number).padStart(2, "0")}</strong><Source>{bayState(data, b, now)}</Source><span className="text-xs muted">{b.connector} · Relay {b.relayChannel}</span></Link>)}</div><h3 className="text-lg mt-7">While you recharge</h3><p className="muted text-sm mt-3">{s.amenities.join(" · ")}</p></div><section className="panel h-fit credit-form"><Source>{isDemo ? "DEMO MODE" : "BACKEND DATA"}</Source><h2 className="text-2xl">Connect. Confirm. Charge.</h2><p className="text-sm muted">Arrive at the station and connect your plug before starting. Choose the bay number printed at the charger.</p><div className="data-row"><span>Station / ESP32</span><span>{s.online ? "Online" : "Offline"} / {deviceFresh(data,s.deviceId,now) ? "Online" : "Offline / stale"}</span></div><div className="data-row"><span>Primary device</span><strong>{s.deviceId}</strong></div><div className="data-row"><span>Last seen</span><span>{device ? timestamp(device.lastSeen) : "Unavailable"}</span></div><div className="data-row"><span>Price per kWh</span><strong>{credits(s.priceMinor)}</strong></div><div className="data-row"><span>Opening hours</span><span>{s.openingHours}</span></div><a className="action action-outline" href={`https://www.google.com/maps/dir/?api=1&destination=${s.lat},${s.lng}`} target="_blank" rel="noreferrer">Get directions <ArrowUpRight size={14} /></a><Link className="action action-primary" href={`/charge?station=${id}`}>Connect and Start</Link><p className="text-xs muted">Your available wallet balance limits this session. Only delivered energy is debited.</p></section></div></div></PublicShell>;
}
