"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowUpRight, Wallet, ShieldCheck, CheckCircle2, Clock3, XCircle } from "lucide-react";
import { useAuth } from "@/components/shared/providers";
import { useCreditData } from "@/store/credit-store";
import { credits, bdt, decimal, parseCredits, validateTopup } from "@/lib/credit/money";
import { walletView } from "@/lib/credit/selectors";
import { creditService } from "@/lib/credit/services";
import type { Ledger, Payment } from "@/lib/credit/model";
import { isDemo } from "@/lib/config";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Heading, Source, timestamp, Action } from "./ui";
import { TopupReceipt, ChargingReceipt } from "./receipt";
import { Sheet, SheetContent, SheetTitle, SheetDescription } from "@/components/ui/sheet";
import { DataGrid } from "@/components/admin/shared";

export function LedgerList({ rows }: { rows: Ledger[] }) { return <div className="credit-ledger">{rows.length ? rows.map(l => <div className="credit-ledger-item" key={l.id}><div><strong className="capitalize">{l.kind.replaceAll("-", " ")}</strong><p className="text-xs muted mt-2">{l.reason}</p><small>{timestamp(l.at)} · {l.reference}</small>{l.sandbox && <Source>SANDBOX</Source>}</div><div className="text-right"><strong>{l.amountMinor > 0 ? "+" : ""}{credits(l.amountMinor)}</strong><small>Balance {decimal(l.balanceAfterMinor)}</small><small>Posted</small></div></div>) : <p className="empty-state">Your credit activity will appear here.</p>}</div>; }
export function WalletOverview() {
  const { user } = useAuth(); const data = useCreditData(); if (!user) return null;
  const wallet = walletView(data, user.id); const rows = data.ledger.filter(l => l.userId === user.id); const active = data.sessions.find(s => s.ownerId === user.id && s.state !== "completed");
  return <><Heading title="Power, in your pocket." description="One wallet. Every charge. 1 BDT = 1 HelioBay Credit." action={<Link className="action action-dark" href="/wallet/top-up">Add Credits <ArrowUpRight size={14} /></Link>} /><div className="credit-split"><section className="credit-hero"><Wallet className="mt-6" size={26} /><p className="text-xs mt-4 muted">Current balance</p><h2 data-testid="wallet-balance">{credits(wallet.balanceMinor)}</h2><p className="text-xs muted">Amounts include your active session’s accrued cost.</p><div className="grid grid-cols-2 gap-6 mt-8"><div><small className="muted">Reserved credits</small><p className="text-lg mt-2">{decimal(wallet.reservedMinor)}</p></div><div><small className="muted">Available credits</small><p className="text-lg mt-2">{decimal(wallet.availableMinor)}</p></div></div></section><section className="panel"><h2 className="panel-title">Only pay for the energy you use.</h2><p className="text-sm muted mt-4 leading-7">Your available credits are held when charging starts. Unused credits are released automatically after your session. Your balance never goes below zero.</p><p className="notice mt-5"><ShieldCheck size={16} className="inline mr-2" />Top-ups start at 10 Credits through SSLCOMMERZ Sandbox. No real money moves in this sandbox.</p>{active && <Link href={`/charging/${active.id}`} className="action action-outline w-full mt-5">View active charging session</Link>}</section></div>{wallet.balanceMinor < 1000 && <p className="notice credit-low mt-5">Low credit. Add Credits before your next charge.</p>}<section className="panel credit-page-section"><div className="panel-top"><h2 className="panel-title">Recent wallet activity</h2><Link className="text-xs underline" href="/wallet/transactions">View full ledger</Link></div><LedgerList rows={rows.slice(0, 5)} /></section><section className="panel"><h2 className="panel-title">Your charging spend</h2><div className="metric-grid">{[7, 30, 90].map(days => { const spent = rows.filter(l => l.kind === "charging-debit" && Date.now() - Date.parse(l.at) < days * 86400000).reduce((n, l) => n - l.amountMinor, 0); return <div key={days}><small className="muted">Last {days} days</small><strong className="block text-xl mt-2">{credits(spent)}</strong></div>; })}</div><Link className="text-xs underline" href="/history">View charging history →</Link></section></>;
}
export function WalletTransactions({ admin = false, userId }: { admin?: boolean; userId?: string }) {
  const { user } = useAuth(); const data = useCreditData(); const [kind, setKind] = useState("all"); const [selected, setSelected] = useState<Ledger | null>(null); const id = userId ?? user?.id;
  const rows = data.ledger.filter(l => (admin && !userId || l.userId === id) && (kind === "all" || l.kind === kind));
  return <><Heading title="Every credit, accounted for." description="An auditable ledger of purchases, energy charges, adjustments and reversals." /><DataGrid name="wallet transactions" rows={rows} onInspect={setSelected} columns={[{ label: "Type", value: l => l.kind }, { label: "Amount", value: l => credits(l.amountMinor) }, { label: "Balance after", value: l => credits(l.balanceAfterMinor) }, { label: "Reference", value: l => l.reference }, { label: "Status", value: l => `${l.status}${l.sandbox ? " · SANDBOX" : ""}` }, { label: "Recorded", value: l => timestamp(l.at) }, { label: "Reason", value: l => l.reason }]} filters={<select className="credit-filter" aria-label="Transaction kind" value={kind} onChange={e => setKind(e.target.value)}>{["all", "top-up", "charging-debit", "adjustment", "reversal"].map(k => <option key={k} value={k}>{k}</option>)}</select>} /><Sheet open={Boolean(selected)} onOpenChange={open => { if (!open) setSelected(null); }}><SheetContent className="admin-detail-sheet"><SheetTitle>Wallet transaction</SheetTitle><SheetDescription>Recorded credit movement and its supporting receipt.</SheetDescription>{selected?.kind === "charging-debit" ? <ChargingReceipt sessionId={selected.reference} /> : selected?.kind === "top-up" ? <TopupReceipt paymentId={selected.reference} /> : selected && <div className="credit-form"><p className="break-all">{selected.reference}</p><p>{selected.reason}</p><strong>{credits(selected.amountMinor)}</strong><p>Balance after: {credits(selected.balanceAfterMinor)}</p><p>{timestamp(selected.at)} · Posted</p></div>}</SheetContent></Sheet></>;
}
export function Topup() {
  const data = useCreditData(); const [amount, setAmount] = useState("200.00"); const [error, setError] = useState(""); const [summary, setSummary] = useState<number | null>(null); const [busy, setBusy] = useState(false); const [requestId, setRequestId] = useState(() => crypto.randomUUID());
  async function pay() { if (summary === null) return; setBusy(true); setError(""); try { const result = await creditService.wallet.topup(summary, requestId); window.location.assign(result.GatewayPageURL); } catch (e) { setError((e as Error).message); setBusy(false); } }
  return <><Heading title="A little credit. A long way." description="Top up securely through SSLCOMMERZ Sandbox. 1 BDT = 1 Credit." /><div className="credit-split"><section className="panel"><form className="credit-form" onSubmit={e => { e.preventDefault(); try { const minor = parseCredits(amount); validateTopup(minor, data.policy.maxTopupMinor); setSummary(minor); setError(""); } catch (e) { setError((e as Error).message); } }}><div className="credit-preset">{[100, 200, 500, 1000].map(n => <Button type="button" key={n} variant={amount === `${n}.00` ? "default" : "outline"} onClick={() => { setAmount(`${n}.00`); setRequestId(crypto.randomUUID()); }}>{n} Credits</Button>)}</div><label>Custom amount (Credits)<Input inputMode="decimal" value={amount} onChange={e => { setAmount(e.target.value); setRequestId(crypto.randomUUID()); }} /></label><p className="text-xs muted">Minimum 10.00 · Maximum {credits(data.policy.maxTopupMinor)}</p>{error && <p role="alert" className="error-text">{error}</p>}<Button type="submit">Review top-up</Button></form></section><section className="credit-hero"><Source>SANDBOX</Source><h2>Your credit.<br />Your control.</h2><p className="muted text-sm leading-7">A successful return page is not proof of payment. Credits are added only after the payment service verifies the transaction.</p><p className="muted text-xs mt-6">SSLCOMMERZ credentials stay on the backend. This website never asks for your wallet PIN or bank password.</p></section></div><Dialog open={summary !== null} onOpenChange={open => { if (!open && !busy) setSummary(null); }}><DialogContent><DialogTitle>Confirm your top-up</DialogTitle><DialogDescription>Payment is processed through SSLCOMMERZ Sandbox.</DialogDescription><div className="data-row"><span>You receive</span><strong>{credits(summary ?? 0)}</strong></div><div className="data-row"><span>Sandbox payment</span><strong>{bdt(summary ?? 0)}</strong></div>{isDemo && <p className="notice">You will enter a clearly labelled local gateway simulator. It is not the real SSLCOMMERZ website.</p>}{error && <p className="error-text" role="alert">{error}</p>}<Button disabled={busy} onClick={pay}>{busy ? "Creating payment session…" : "Continue to SSLCOMMERZ Sandbox"}</Button><Button variant="outline" disabled={busy} onClick={() => setSummary(null)}>Change amount</Button></DialogContent></Dialog></>;
}
export function SandboxPayment({ id }: { id: string }) {
  const data = useCreditData(); const router = useRouter(); const { user } = useAuth(); const payment = data.payments.find(p => p.id === id && p.userId === user?.id);
  if (!isDemo || !payment) return <div className="empty-state"><h1>Demo payment unavailable.</h1><Link href="/wallet" className="action action-outline">Return to wallet</Link></div>;
  async function submit(outcome: "success" | "failure" | "cancel" | "pending") { await creditService.wallet.submitDemo(id, outcome); router.push(`/payment/${outcome === "failure" ? "fail" : outcome === "cancel" ? "cancel" : "success"}?paymentId=${encodeURIComponent(id)}`); }
  return <section className="panel credit-result"><Source>Sandbox payment</Source><h1 className="mt-5">Payment simulator.</h1><p className="muted text-sm mt-4 leading-7">This local screen demonstrates gateway outcomes. It is not operated by SSLCOMMERZ and does not collect payment credentials.</p><div className="data-row mt-5"><span>Top-up</span><strong>{credits(payment.amountMinor)}</strong></div><div className="credit-form mt-5"><Action variant="default" run={() => submit("success")}>Simulate successful payment</Action><Action run={() => submit("pending")}>Simulate pending verification</Action><Action run={() => submit("failure")}>Simulate payment failure</Action><Action run={() => submit("cancel")}>Cancel sandbox payment</Action></div></section>;
}
export function PaymentResult({ id }: { id?: string }) {
  const [payment, setPayment] = useState<Payment | null>(null); const [error, setError] = useState(""); const [attempt, setAttempt] = useState(0); const [waiting, setWaiting] = useState(false);
  useEffect(() => { const controller = new AbortController(); let timer: ReturnType<typeof setTimeout>; let tries = 0; let disposed = false;
    async function check() { if (!id) { setError("A valid payment reference is required. A callback URL alone cannot add credits."); return; } try { const result = await creditService.wallet.payment(id, controller.signal); if (disposed) return; setPayment(result); setError(""); if (result.status === "pending" && ++tries < 15) timer = setTimeout(check, 2000); else setWaiting(result.status === "pending"); } catch (e) { if (!disposed) setError((e as Error).message); } }
    void check(); return () => { disposed = true; controller.abort(); clearTimeout(timer); };
  }, [id, attempt]);
  const verified = payment?.status === "verified"; const failed = payment?.status === "failed" || payment?.status === "cancelled";
  return <><section className="panel credit-result text-center"><Source>SANDBOX</Source>{verified ? <CheckCircle2 size={40} className="mx-auto text-green-700 mt-6" /> : failed ? <XCircle size={40} className="mx-auto mt-6 text-red-700" /> : <Clock3 size={40} className="mx-auto mt-6 text-green-700" />}<h1 className="mt-5" aria-live="polite">{verified ? "Credits, ready to go." : failed ? payment.status === "cancelled" ? "Payment cancelled." : "Payment not completed." : "Verifying payment."}</h1><p className="text-sm muted mt-4 leading-7">{verified ? `${credits(payment.amountMinor)} added after verified payment. Duplicate callbacks do not add credit twice.` : failed ? "No credits were added. You can safely create a new top-up." : "Waiting for verified payment status. Your balance will change only after backend validation/IPN is complete."}</p>{error && <p className="notice credit-low mt-5" role="alert">{error}</p>}{waiting && <p className="notice mt-5">Verification is still pending. Check again later; do not pay twice.</p>}<div className="credit-actions justify-center mt-6"><Link href="/wallet" className="action action-primary">Return to wallet</Link>{failed && <Link href="/wallet/top-up" className="action action-outline">Try another top-up</Link>}{(!verified && !failed || error) && <Button variant="outline" onClick={() => { setWaiting(false); setAttempt(x => x + 1); }}>Check payment status</Button>}</div><p className="text-[10px] muted mt-5 break-all">Reference: {id ?? "Missing"}</p></section>{verified && payment && <TopupReceipt paymentId={payment.id} />}</>;
}
