import { beforeAll,afterAll,describe,it,expect } from 'vitest';
import { isolatedDatabase } from './helpers/database.js';
import { chargingFixture,telemetry } from './helpers/charging.js';
const url=process.env.TEST_DATABASE_URL;
describe.skipIf(!url)('charging safety and finalization',()=>{
 let ctx:Awaited<ReturnType<typeof isolatedDatabase>>;
 beforeAll(async()=>{ctx=await isolatedDatabase(url!);},30000);afterAll(async()=>ctx?.close());
 it.each(['BATTERY_FULL','PLUG_DISCONNECTED','CREDIT_EXHAUSTED','SAFETY_FAULT','MAX_ENERGY_REACHED','MAX_DURATION_REACHED'] as const)('requests stop for %s',async reason=>{
  const f=await chargingFixture(ctx.db,reason==='CREDIT_EXHAUSTED'?1:1000);if(reason==='MAX_ENERGY_REACHED')f.config.MAX_SESSION_ENERGY_MWH='1000';const s=await f.start();await f.ack(s.id);
  if(reason==='MAX_DURATION_REACHED')await ctx.db.chargingSession.update({where:{id:s.id},data:{startedAt:new Date(Date.now()-15000000)}});
  const t={...telemetry(),bayId:f.bay.code,sessionId:s.id,relayOn:true,chargingPowerW:1000,chargingCurrentMa:20000,energyMWh:'500',...(reason==='BATTERY_FULL'?{vehicleBatteryPercent:100,chargingCurrentMa:0}:{}),...(reason==='PLUG_DISCONNECTED'?{vehicleBatteryMv:0}:{}),...(reason==='SAFETY_FAULT'?{chargingVoltageMv:950000}:{})};
  await f.engine.telemetry(f.device.id,t);const result=await ctx.db.chargingSession.findUniqueOrThrow({where:{id:s.id}});expect(result.status).toBe('STOP_PENDING');expect(result.stopReason).toBe(reason);expect(await ctx.db.deviceCommand.count({where:{sessionId:s.id,type:'STOP'}})).toBe(1);
 });
 it('caps final cost, never debits below zero, and closes a small reservation',async()=>{const f=await chargingFixture(ctx.db,1),s=await f.start();await f.ack(s.id);await f.engine.telemetry(f.device.id,{...telemetry(),bayId:f.bay.code,sessionId:s.id,energyMWh:'2000',final:true});const result=await ctx.db.chargingSession.findUniqueOrThrow({where:{id:s.id}});expect(result.costMinor).toBe(1n);expect(result.endingBalanceMinor).toBe(0n);expect(result.completedAt).not.toBeNull();});
 it('does not settle a backward meter or a STOP acknowledgement without final telemetry',async()=>{const f=await chargingFixture(ctx.db),s=await f.start();await f.ack(s.id);await f.engine.telemetry(f.device.id,{...telemetry(),bayId:f.bay.code,sessionId:s.id,energyMWh:'1000',relayOn:true});await f.engine.stop(s.id,f.owner.id,'USER_STOPPED','safe-stop','req');const cmd=await ctx.db.deviceCommand.findFirstOrThrow({where:{sessionId:s.id,type:'STOP'}});await f.engine.acknowledge(f.device.id,{kind:'ack',commandId:cmd.id,sessionId:s.id,bootId:'boot',sequence:'10',at:new Date().toISOString(),dataSource:'SIMULATOR',accepted:true,relayOn:false,energyMWh:'1000'});await f.engine.telemetry(f.device.id,{...telemetry(),bayId:f.bay.code,sessionId:s.id,energyMWh:'500',final:true});expect((await ctx.db.chargingSession.findUniqueOrThrow({where:{id:s.id}})).completedAt).toBeNull();expect((await ctx.db.creditReservation.findUniqueOrThrow({where:{sessionId:s.id}})).status).toBe('HELD');});
 it('records emergency stop and offline interruption without releasing credit',async()=>{const f=await chargingFixture(ctx.db),s=await f.start();await f.ack(s.id);await f.engine.handle(f.device.id,{kind:'event',bootId:'boot',sequence:'8',at:new Date().toISOString(),dataSource:'SIMULATOR',bayId:f.bay.code,event:'EMERGENCY_STOP',code:'EMERGENCY_STOP'});expect((await ctx.db.chargingSession.findUniqueOrThrow({where:{id:s.id}})).stopReason).toBe('EMERGENCY_STOP');const other=await chargingFixture(ctx.db),os=await other.start();await other.ack(os.id);await ctx.db.device.update({where:{id:other.device.id},data:{lastSeenAt:new Date(0)}});await other.engine.sweep();expect((await ctx.db.chargingSession.findUniqueOrThrow({where:{id:os.id}}))).toMatchObject({status:'INTERRUPTED',stopReason:'DEVICE_OFFLINE',reconciliationRequired:true});});
 it('serializes competing owners for one bay',async()=>{const f=await chargingFixture(ctx.db),other=await chargingFixture(ctx.db);const results=await Promise.allSettled([f.start(),other.engine.start(other.owner.id,{...f.input,vehicleId:other.vehicle.id},'competing-user','req')]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(await ctx.db.chargingSession.count({where:{bayId:f.bay.id,completedAt:null}})).toBe(1);});
});
