import {createServer}from'node:http';import type{DecodedIdToken}from'firebase-admin/auth';import{isolatedDatabase}from'./helpers/database.js';import{chargingFixture,deviceKey}from'./helpers/charging.js';import{DeviceIngress}from'../src/modules/iot/ingress.js';import{MqttGateway}from'../src/modules/iot/gateway.js';import{ChargingEngine}from'../src/modules/sessions/engine.js';import{readIotConfig}from'../src/config/iot.js';import{startSimulator}from'../src/modules/simulator/mqtt.js';import{attachRealtime}from'../src/modules/realtime/server.js';import{createApp,finishApp}from'../src/app.js';import{envSchema}from'../src/config/env.js';import{mountApi}from'../src/routes.js';import{PaymentService}from'../src/modules/payments/service.js';import{PaymentSettlement}from'../src/modules/payments/settlement.js';import{paymentConfigSchema}from'../src/config/payments.js';
if(process.env.NODE_ENV!=='test'||!process.env.TEST_DATABASE_URL?.includes('_test')||process.env.FULL_STACK_TEST!=='true')throw new Error('Full-stack test server is test-only');
const ctx=await isolatedDatabase(process.env.TEST_DATABASE_URL),fixture=await chargingFixture(ctx.db,50000);await ctx.db.user.update({where:{id:fixture.owner.id},data:{email:'owner@heliobay.test',phone:'01700000000',city:'Dhaka'}});
const config=readIotConfig({NODE_ENV:'test',ALLOW_DEVICE_SIMULATOR:'true',MQTT_URL:process.env.MQTT_TEST_URL,MQTT_TLS_ENABLED:'false',MQTT_CLIENT_ID:`browser-${crypto.randomUUID()}`,TELEMETRY_SAMPLE_INTERVAL_MS:'100',TELEMETRY_INTERVAL_MS:'100'});
const runtime:{engine?:ChargingEngine}={};
const ingress:DeviceIngress=new DeviceIngress(ctx.db,config,fixture.bus,(id,m)=>runtime.engine!.handle(id,m),()=>deviceKey);
const gateway:MqttGateway=new MqttGateway(config,ingress);
const engine=new ChargingEngine(ctx.db,config,fixture.bus,gateway,()=>deviceKey);runtime.engine=engine;
const paymentGateway={initiate:async()=>({sessionKey:'test-only',gatewayPageUrl:'https://sandbox.sslcommerz.com/test-checkout'}),validate:async(valId:string)=>{const p=await ctx.db.paymentTransaction.findUniqueOrThrow({where:{id:valId}});const amount=`${p.amountMinor/100n}.${(p.amountMinor%100n).toString().padStart(2,'0')}`;return{tran_id:p.id,val_id:valId,status:'VALID',amount,currency_amount:amount,currency:'BDT',currency_type:'BDT',risk_level:0};},lookup:async()=>[]};
const testPaymentConfig=paymentConfigSchema.parse({SSLCOMMERZ_STORE_ID:'test-store',SSLCOMMERZ_STORE_PASSWORD:'test-password',PUBLIC_APP_URL:'http://127.0.0.1:3008',API_PUBLIC_URL:'http://127.0.0.1:4008'});const jwt=(uid:string,email:string)=>{const now=Math.floor(Date.now()/1000);return [Buffer.from('{"alg":"none"}').toString('base64url'),Buffer.from(JSON.stringify({sub:uid,user_id:uid,email,email_verified:true,iat:now,exp:now+3600,auth_time:now,firebase:{sign_in_provider:'password'}})).toString('base64url'),'test-signature'].join('.');};const payments=new PaymentService(ctx.db,paymentGateway,testPaymentConfig),ownerToken=jwt(fixture.owner.firebaseUid,'owner@heliobay.test'),adminToken=jwt(fixture.admin.firebaseUid,'admin@heliobay.test');
const verify=async(token:string)=>{const record=token===ownerToken?fixture.owner:token===adminToken?fixture.admin:null;if(!record)throw new Error('Unknown test token');const now=Math.floor(Date.now()/1000);return{uid:record.firebaseUid,sub:record.firebaseUid,aud:'test',iss:'https://securetoken.google.com/test',email:record.email??undefined,email_verified:true,name:record.name,iat:now,exp:now+3600,auth_time:now,firebase:{identities:{email:record.email?[record.email]:[]},sign_in_provider:'password'}}as DecodedIdToken;};
// Accelerated hardware/browser integration compresses minutes of telemetry and UI
// refreshes into seconds, so only this isolated test server receives a higher cap.
const app=createApp(envSchema.parse({NODE_ENV:'test',DATABASE_URL:process.env.TEST_DATABASE_URL,CORS_ORIGINS:'http://127.0.0.1:3008',FIREBASE_PROJECT_ID:'test',LOG_LEVEL:'silent'}),undefined,{apiRateLimit:2_000});mountApi(app,ctx.db,verify,payments,engine);
app.get('/__test/context',async(_req,res)=>res.json({ownerToken,adminToken,stationId:fixture.station.id,bayId:fixture.bay.id,vehicleId:fixture.vehicle.id,paymentId:(await ctx.db.paymentTransaction.findFirst({where:{userId:fixture.owner.id},orderBy:{createdAt:'desc'}}))?.id}));app.post('/__test/payments/:id/settle',async(req,res,next)=>{try{res.json(await new PaymentSettlement(payments).validate(req.params.id!,req.params.id!));}catch(e){next(e);}});finishApp(app);
const server=createServer(app),realtime=attachRealtime(server,ctx.db,verify,fixture.bus,['http://127.0.0.1:3008']);await new Promise<void>(r=>server.listen(4008,'127.0.0.1',r));gateway.start();const simulator=startSimulator({url:process.env.MQTT_TEST_URL!,secret:deviceKey,stationId:fixture.station.code,deviceId:fixture.device.publicId,bayId:fixture.bay.code,relayChannel:1,speed:1,scenario:'normal',intervalMs:250,allowed:true,nodeEnv:'test'});const worker=setInterval(()=>void engine.dispatch().then(()=>engine.sweep()),100);console.log('FULLSTACK_READY');
const close=async()=>{clearInterval(worker);await Promise.race([(async()=>{await simulator.close();await gateway.close();await realtime.close();await new Promise<void>(r=>server.close(()=>r()));await ctx.close();})(),new Promise(r=>setTimeout(r,2000))]);process.exit(0);};process.on('SIGINT',()=>void close());process.on('SIGTERM',()=>void close());
