import { describe,it,expect } from 'vitest';
import { SimulatedDevice,type Scenario } from '../src/modules/simulator/device.js';
import { startSimulator } from '../src/modules/simulator/mqtt.js';
import type { DeviceMessage } from '../src/modules/iot/protocol.js';
const setup=(scenario:Scenario,maximum='1000000')=>{const messages:DeviceMessage[]=[];const device=new SimulatedDevice({stationId:'ST001',deviceId:'ESP32-ST001',bayId:'BAY01',relayChannel:1,speed:10,scenario},async m=>{messages.push(m);});const command={commandId:'start-1',type:'START',sessionId:'session-1',stationId:'ST001',deviceId:'ESP32-ST001',bayId:'BAY01',relayChannel:1,maxCostMinor:'1000',maxEnergyMWh:maximum,maxDurationSeconds:1000,telemetryIntervalMs:1000,dataSource:'SIMULATOR',issuedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+60000).toISOString()};return {device,messages,command};};
describe('deterministic device simulator',()=>{
 it.each(['normal','unplug','battery-full','sensor-fault','emergency-stop'] as const)('stops locally for %s',async scenario=>{const f=setup(scenario);await f.device.connect();await f.device.step(1000);await f.device.command(f.command);for(let i=0;i<12;i++)await f.device.step(1000);expect(f.messages.at(-1)).toMatchObject({kind:'telemetry',relayOn:false,final:true,dataSource:'SIMULATOR'});if(scenario==='unplug')expect(f.messages.at(-1)).toMatchObject({plugConnected:false});if(scenario==='emergency-stop')expect(f.messages.some(m=>m.kind==='event'&&m.event==='EMERGENCY_STOP')).toBe(true);});
 it('caps local energy, ignores expired commands and never restarts a duplicate',async()=>{const f=setup('credit-exhausted','1000');await f.device.step(1000);await f.device.command({...f.command,expiresAt:new Date(0).toISOString()});expect(f.messages.some(m=>m.kind==='ack')).toBe(false);await f.device.command(f.command);await f.device.step(1000);await f.device.command(f.command);expect(f.messages.at(-1)).toMatchObject({energyMWh:'1000',relayOn:false,final:true});});
 it('reports failed start without energizing relay',async()=>{const f=setup('command-failure');await f.device.step(1000);await f.device.command(f.command);expect(f.messages.at(-1)).toMatchObject({kind:'ack',accepted:false,relayOn:false,energyMWh:'0'});});
 it('continues local cutoff after timeout is signaled',async()=>{const f=setup('timeout','12000');await f.device.step(1000);await f.device.command(f.command);for(let i=0;i<5;i++)await f.device.step(1000);expect(f.messages.at(-1)).toMatchObject({relayOn:false,energyMWh:'12000',final:true});});
 it('cannot run in production',()=>{expect(()=>startSimulator({url:'mqtt://localhost',secret:'x'.repeat(32),stationId:'ST001',deviceId:'D1',bayId:'BAY01',relayChannel:1,speed:1,scenario:'normal',allowed:true,nodeEnv:'production'})).toThrow();});
});
