"use client";
import { useState } from "react";
import { toast } from "sonner";
import { useDemoStore } from "@/store/demo-store";
import { platform } from "@/lib/platform";
import { dateTime } from "@/lib/services/booking-rules";
import { AdminHeading, ConfirmAction, DataGrid, Status, useUnsaved } from "./shared";
import { Sheet, SheetContent, SheetTitle, SheetDescription } from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";

export function AdminMaintenance() {
  const n = useDemoStore(s => s.network); const [filter, setFilter] = useState("open"); const [severity, setSeverity] = useState("all");
  const [selected, setSelected] = useState<string | null>(null); const [note, setNote] = useState(""); const [deviceId, setDeviceId] = useState("ST001"); const [busy, setBusy] = useState(false);
  const close = useUnsaved(Boolean(note)); const fault = n.faults.find(f => f.id === selected);
  return <>
    <AdminHeading title="Keep good energy flowing." description="Triage faults, record maintenance and retain a clear operational trail." />
    <DataGrid name="faults" rows={n.faults.filter(f => (filter === "all" || filter === "open" ? filter === "all" || f.status !== "resolved" : f.status === "resolved") && (severity === "all" || f.severity === severity))} columns={[
      { label: "Fault", value: f => f.code }, { label: "Device", value: f => f.deviceId }, { label: "Severity", value: f => f.severity, render: f => <Status danger={f.severity === "critical"}>{f.severity}</Status> },
      { label: "Message", value: f => f.message }, { label: "Status", value: f => f.status }, { label: "Detected", value: f => dateTime(f.createdAt) },
    ]} filters={<><select aria-label="Fault status" value={filter} onChange={e => setFilter(e.target.value)}><option value="open">Open & acknowledged</option><option value="resolved">Resolved</option><option value="all">All faults</option></select><select aria-label="Fault severity" value={severity} onChange={e => setSeverity(e.target.value)}><option value="all">All severity</option><option value="critical">Critical</option><option value="warning">Warning</option></select></>} onInspect={f => { if (close()) { setNote(""); setSelected(f.id); } }} />
    <div className="dashboard-grid mt-6"><section className="panel"><h2 className="panel-title">Maintenance log</h2><form className="mt-5" onSubmit={async e => { e.preventDefault(); setBusy(true); try { await platform.admin.addMaintenance(deviceId, note); setNote(""); toast.success("Maintenance note recorded."); } catch (e) { toast.error((e as Error).message); } finally { setBusy(false); } }}><label className="text-xs">Device<select className="w-full mt-2 mb-4" value={deviceId} onChange={e => setDeviceId(e.target.value)}>{n.devices.map(d => <option key={d.id}>{d.id}</option>)}</select></label><label className="text-xs">Maintenance notes<textarea required minLength={5} maxLength={2000} className="admin-textarea mt-2" value={selected ? "" : note} onChange={e => { setSelected(null); setNote(e.target.value); }} placeholder="Inspection, repair or follow-up performed…" /></label><Button className="mt-4" type="submit" disabled={busy || !note || Boolean(selected)}>{busy ? "Saving…" : "Save maintenance note"}</Button></form><div className="mt-5">{n.maintenance.slice(0, 8).map(m => <article className="border-t py-4" key={m.id}><p className="text-xs muted">{m.deviceId} · {dateTime(m.createdAt)}</p><p className="text-sm mt-2">{m.note}</p></article>)}{!n.maintenance.length && <p className="muted text-xs">No maintenance notes yet.</p>}</div></section><section className="panel"><h2 className="panel-title">Audit trail</h2><div className="audit-timeline">{n.audit.slice(0, 30).map(a => <article key={a.id}><p className="text-sm font-medium">{a.action}</p><p className="text-xs muted mt-1">{a.targetId} · {dateTime(a.createdAt)}</p><p className="text-xs mt-2 break-words">{a.detail}</p><small className="muted">By {a.actorId}</small></article>)}{!n.audit.length && <p className="muted text-sm">Actions will appear here as you operate the network.</p>}</div></section></div>
    <Sheet open={Boolean(fault)} onOpenChange={v => { if (!v && close()) { setSelected(null); setNote(""); } }}><SheetContent className="admin-detail-sheet"><SheetTitle>{fault?.code} · {fault?.deviceId}</SheetTitle><SheetDescription>{fault?.message}</SheetDescription>{fault && <><Status danger={fault.severity === "critical"}>{fault.severity} · {fault.status}</Status><p className="text-xs muted">Detected {dateTime(fault.createdAt)}. Last updated {dateTime(fault.updatedAt)}.</p><label className="text-sm">Resolution / acknowledgement note<textarea className="admin-textarea mt-2" minLength={5} maxLength={2000} value={note} onChange={e => setNote(e.target.value)} /></label><div className="flex gap-3 flex-wrap"><ConfirmAction label="Acknowledge fault" disabled={fault.status !== "open" || note.trim().length < 5} title="Acknowledge this fault?" description="Acknowledgement does not clear a blocking fault. Charging remains blocked until resolution." action={async () => { await platform.admin.updateFault(fault.id, "acknowledged", note); setNote(""); }} /><ConfirmAction label="Resolve fault" disabled={fault.status === "resolved" || note.trim().length < 5} title="Resolve this fault?" description="Confirm the device has been inspected. This resets a simulated sensor/emergency fault; charging must be restarted explicitly." action={async () => { await platform.admin.updateFault(fault.id, "resolved", note); setNote(""); }} /></div><h3 className="mt-5 text-lg">Fault timeline</h3>{n.maintenance.filter(m => m.faultId === fault.id).map(m => <div key={m.id} className="notice"><p className="text-xs muted">{dateTime(m.createdAt)}</p><p>{m.note}</p></div>)}</>}</SheetContent></Sheet>
  </>;
}
