"use client";
import { useState } from "react";
import dynamic from "next/dynamic";
import Link from "next/link";
import { ArrowUpRight, Sun, Zap, Leaf, Radio, Grid2X2, Wallet } from "lucide-react";
import { useDemoStore } from "@/store/demo-store";
import { useClock } from "@/hooks/use-clock";
import { allBookings, allPayments, allSessions, stationSnapshot } from "@/lib/platform/selectors";
import { analytics, dhakaDay } from "@/lib/platform/analytics";
import { dateTime, money } from "@/lib/services/booking-rules";
import { liveStation } from "@/lib/services/stations";
import { AdminHeading, Status } from "./shared";
import { EnergyFlow } from "@/components/charging/energy-flow";
import { Skeleton } from "@/components/ui/skeleton";

const Chart = dynamic(() => import("./charts"), { loading: () => <Skeleton className="h-72" /> });
const StationMap = dynamic(() => import("@/components/stations/station-map"), { ssr: false, loading: () => <Skeleton className="h-80 w-full" /> });
export function AdminOverview() {
  const network = useDemoStore(s => s.network); const owners = useDemoStore(s => s.owners); const now = useClock(); const [selected, setSelected] = useState("green-point");
  const data = { network, owners }; const bookings = allBookings(data); const sessions = allSessions(data); const payments = allPayments(data);
  const stations = network.stations.map(s => liveStation(stationSnapshot(data, s.id)!, bookings, now));
  const active = sessions.filter(s => s.status !== "completed"); const alerts = network.faults.filter(f => f.status !== "resolved");
  const today = dhakaDay(new Date(now || 0).toISOString()); const from = new Date(Date.parse(today) - 6 * 86400000).toISOString().slice(0, 10);
  const series = analytics(data, from, today); const energy = sessions.reduce((n, s) => n + s.energy, 0); const solar = sessions.reduce((n, s) => n + s.energy * s.solar / 100, 0);
  const chosen = stations.find(s => s.id === selected);
  return <>
    <AdminHeading title="Good energy. Under control." description="A live view of the places, people and devices powering your network." action={<Link href="/admin/devices" className="action action-dark"><CpuIcon />Device control <ArrowUpRight size={15} /></Link>} />
    <div className="admin-metrics">{[
      { label: "Active stations", value: `${stations.filter(s => s.online && !s.maintenance).length}/${stations.length}`, sub: "Connected to your network", icon: Radio },
      { label: "Available bays", value: stations.reduce((n, s) => n + s.available, 0), sub: "Ready for the next arrival", icon: Grid2X2 },
      { label: "Active sessions", value: active.length, sub: `${active.filter(s => s.status === "charging").length} delivering energy`, icon: Zap },
      { label: "Today’s net receipts", value: money(series.at(-1)?.revenue ?? 0), sub: "Payments less refunds · simulation", icon: Wallet },
    ].map(m => <div className="panel" key={m.label}><div className="flex justify-between items-center text-xs muted"><span>{m.label}</span><m.icon size={17} /></div><strong className="text-3xl block mt-5 tracking-tight">{m.value}</strong><p className="text-[10px] muted mt-2">{m.sub}</p></div>)}</div>
    <div className="dashboard-grid mt-6"><section className="panel !p-0 overflow-hidden"><div className="p-6 flex items-center justify-between"><div><h2 className="panel-title">Your network, at a glance.</h2><p className="text-xs muted mt-2">Select a station to inspect availability.</p></div><Link href="/admin/stations" aria-label="Manage all stations"><ArrowUpRight size={17} /></Link></div><div className="admin-map"><StationMap stations={stations} selected={selected} onSelect={setSelected} /></div><div className="p-5 flex justify-between items-center gap-4">{chosen ? <><div><strong className="text-sm">{chosen.name}</strong><p className="muted text-xs mt-1">{chosen.available} bays available · {chosen.solar}% solar</p></div><Link className="action action-outline !text-xs" href={`/admin/stations/${chosen.id}`}>Inspect station</Link></> : <p className="muted">Select a marker.</p>}</div></section><section className="panel admin-energy-panel"><Sun size={24} /><p className="eyebrow !mt-6 !mb-3">SOLAR FIRST. ALWAYS.</p><h2 className="text-3xl tracking-tight">From sunshine<br />to the next journey.</h2><EnergyFlow /><div className="grid grid-cols-2 gap-5 mt-7"><div><strong className="text-3xl">{energy ? Math.round(solar / energy * 100) : 0}%</strong><p className="text-xs mt-2">Renewable energy</p></div><div><strong className="text-3xl">{(solar * .4).toFixed(1)} kg</strong><p className="text-xs mt-2">Illustrative CO₂ avoided</p></div></div><p className="text-[10px] muted mt-5">Weighted by recorded energy. Environmental estimate: solar kWh × 0.4 kg.</p><Link className="text-xs inline-flex items-center gap-2 mt-6" href="/admin/analytics">Explore the impact <ArrowUpRight size={13} /></Link></section></div>
    <div className="dashboard-grid mt-6"><section className="panel"><div className="panel-top"><h2 className="panel-title">Solar & charging demand</h2><Status>Last 7 days</Status></div><Chart data={series} label="EV-equivalent energy (kWh)" series={[{ key: "solar", name: "Solar energy", color: "#00af5a" }, { key: "demand", name: "Charging demand", color: "#93a69a" }]} /></section><section className="panel"><h2 className="panel-title mb-5">Revenue, thoughtfully tracked.</h2><Chart data={series} label="Net simulated receipts (৳)" series={[{ key: "revenue", name: "Net receipts", color: "#197a4a" }]} /></section></div>
    <div className="dashboard-grid mt-6"><section className="panel"><div className="panel-top"><h2 className="panel-title">Live sessions</h2><Link href="/admin/sessions" className="text-xs">View all →</Link></div>{active.length ? active.slice(0, 5).map(s => <Link key={s.id} href="/admin/sessions" className="data-row"><div><strong className="text-xs">{owners[s.ownerId]?.profile.name}</strong><p className="muted text-[10px] mt-1">{s.deviceId} · {s.energy.toFixed(2)} kWh</p></div><Status good={s.status === "charging"}>{s.status}</Status></Link>) : <div className="admin-calm"><Zap size={25} /><p>No active sessions.</p><Link href="/admin/devices">Start a paid demo booking →</Link></div>}<h3 className="panel-title mt-6 mb-3">Upcoming arrivals</h3>{bookings.filter(b => b.status === "upcoming").slice(0, 4).map(b => <Link key={b.id} href="/admin/bookings" className="data-row"><span>{b.id} · {b.bayId}</span><span>{dateTime(b.start)}</span></Link>)}</section><section className="panel"><div className="panel-top"><h2 className="panel-title">Device health & priority alerts</h2><Status danger={alerts.some(f => f.severity === "critical")}>{alerts.length} open</Status></div>{alerts.length ? alerts.slice(0, 4).map(f => <Link key={f.id} href="/admin/maintenance" className="notice mb-3"><strong className="text-xs">{f.deviceId} · {f.severity}</strong><p className="text-xs muted mt-2">{f.message}</p></Link>) : <p className="muted text-sm">No unresolved alerts. Your network is ready.</p>}<div className="data-row mt-5"><span>Devices connected</span><span>{network.devices.filter(d => d.online).length} / {network.devices.length}</span></div><div className="data-row"><span>Station energy generated</span><span>{network.solarWh.toFixed(3)} Wh prototype</span></div><Link href="/admin/maintenance" className="action action-outline mt-5 w-full">Open maintenance center</Link></section></div>
    <section className="panel mt-6"><div className="panel-top"><h2 className="panel-title">Payments & returns</h2><Link href="/admin/payments" className="text-xs">All transactions →</Link></div><div className="admin-activity-grid">{payments.slice(0, 4).map(p => <Link href="/admin/payments" key={p.id} className="notice"><p className="text-xs muted">{p.kind === "refund" ? "Refund" : "Payment"} · {p.method}</p><strong className="block text-2xl mt-3">{p.kind === "refund" ? "−" : "+"}{money(p.amount)}</strong><p className="text-[10px] muted mt-2">{p.bookingId}</p></Link>)}</div></section>
    <div className="flex flex-wrap gap-3 mt-6"><Link href="/admin/stations" className="action action-outline">Manage stations</Link><Link href="/admin/settings" className="action action-outline">Update pricing</Link><Link href="/admin/refunds" className="action action-outline">Review refunds</Link></div>
  </>;
}
function CpuIcon() { return <Leaf size={16} />; }
